export const RPCS = [
  {
    network: "avax",
    name: "Avalanche C Chain Mainnet RPC",
    url: "https://api.avax.network/ext/bc/C/rpc",
    chainId: 43114,
    symbol: "AVAX",
    block_explorer: "https://snowtrace.io",
    type: "Mainnet",
  },
  {
    network: "avax",
    name: "Avalanche C Chain Mainnet RPC",
    url: "https://rpc.ankr.com/avalanche",
    chainId: 43114,
    symbol: "AVAX",
    block_explorer: "https://snowtrace.io",
    type: "Mainnet",
  },
  {
    network: "avax",
    name: "Avalanche FUJI Testnet RPC",
    url: "https://api.avax-test.network/ext/bc/C/rpc",
    chainId: 43113,
    symbol: "AVAX",
    block_explorer: "https://testnet.explorer.avax.network/",
    type: "Testnet",
  },
  {
    network: "avax",
    name: "Avalanche C Chain Local RPC",
    url: "https://localhost:9650/ext/bc/C/rpc",
    chainId: 43112,
    symbol: "AVAX",
    block_explorer: "https://snowtrace.io",
    type: "Testnet",
  },
  {
    network: "bsc",
    name: "Binance Smart Chain Mainnet RPC",
    url: "https://bsc-dataseed.binance.org/",
    chainId: 56,
    symbol: "BNB",
    block_explorer: "https://bscscan.com",
    type: "Mainnet",
  },
  {
    network: "bsc",
    name: "Binance Smart Chain Mainnet RPC",
    url: "https://rpc.ankr.com/bsc",
    chainId: 56,
    symbol: "BNB",
    block_explorer: "https://bscscan.com",
    type: "Mainnet",
  },
  {
    network: "bsc",
    name: "Binance Smart Chain Testnet RPC",
    url: "https://data-seed-prebsc-1-s1.binance.org:8545/",
    chainId: 97,
    symbol: "BNB",
    block_explorer: "https://testnet.bscscan.com",
    type: "Testnet",
  },
  {
    network: "cro",
    name: "Cronos Mainnet RPC",
    url: "https://evm-cronos.crypto.org",
    chainId: 25,
    symbol: "CRO",
    block_explorer: "https://cronos.crypto.org/explorer/",
    type: "Mainnet",
  },
  {
    network: "ela",
    name: "Elastos ETH Mainnet RPC",
    url: "https://api.elastos.io/eth",
    chainId: 20,
    symbol: "ELA",
    block_explorer: "https://explorer.elaeth.io/",
    type: "Mainnet",
  },
  {
    network: "eth",
    name: "Ethereum Mainnet RPC",
    url: "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    chainId: 0x1,
    symbol: "ETH",
    block_explorer: "https://etherscan.io",
    type: "Mainnet",
  },
  {
    network: "eth",
    name: "Ethereum Mainnet RPC",
    url: "https://rpc.ankr.com/eth",
    chainId: 0x1,
    symbol: "ETH",
    block_explorer: "https://etherscan.io",
    type: "Mainnet",
  },
  {
    network: "eth",
    name: "Ethereum Ropsten Testnet RPC",
    url: "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    chainId: 0x3,
    symbol: "ETH",
    block_explorer: "https://ropsten.etherscan.io",
    type: "Testnet",
  },
  {
    network: "eth",
    name: "Ethereum Rinkeby Testnet RPC",
    url: "https://rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    chainId: 0x4,
    symbol: "ETH",
    block_explorer: "https://rinkey.etherscan.io",
    type: "Testnet",
  },
  {
    network: "eth",
    name: "Ethereum Goerli Testnet RPC",
    url: "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    chainId: 0x5,
    symbol: "ETH",
    block_explorer: "https://goerli.etherscan.io",
    type: "Testnet",
  },
  {
    network: "eth",
    name: "Ethereum Kovan Testnet RPC",
    url: "https://kovan.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    chainId: 0x6,
    symbol: "ETH",
    block_explorer: "https://kovan.etherscan.io",
    type: "Testnet",
  },
  {
    network: "ftm",
    name: "Fantom Opera Mainnet RPC",
    url: "https://rpc.ftm.tools/",
    chainId: 0xfa,
    symbol: "FTM",
    block_explorer: "https://ftmscan.com",
    type: "Mainnet",
  },
  {
    network: "ftm",
    name: "Fantom Testnet RPC",
    url: "https://rpc.testnet.fantom.network/",
    chainId: 0xfa2,
    symbol: "FTM",
    block_explorer: "https://testnet.ftmscan.com",
    type: "Testnet",
  },
  {
    network: "fuse",
    name: "Fuse Mainnet RPC",
    url: "https://rpc.fuse.io",
    chainId: 0x7a,
    symbol: "FUSE",
    block_explorer: "https://explorer.fuse.io/",
    type: "Mainnet",
  },
  {
    network: "heco",
    name: "HECO Mainnet RPC",
    url: "https://http-mainnet-node.huobichain.com/",
    chainId: 128,
    symbol: "HT",
    block_explorer: "https://hecoinfo.com/",
    type: "Mainnet",
  },
  {
    network: "heco",
    name: "HECO Testnet RPC",
    url: "https://http-testnet.hecochain.com",
    chainId: 256,
    symbol: "HT",
    block_explorer: "https://testnet.hecoinfo.com/",
    type: "Testnet",
  },
  {
    network: "kcc",
    name: "KCC Mainnet RPC",
    url: "https://rpc-mainnet.kcc.network",
    chainId: 321,
    symbol: "KCS",
    block_explorer: "https://scan.kcc.network",
    type: "Mainnet",
  },
  {
    network: "kcc",
    name: "KCC Testnet RPC",
    url: "https://scan-testnet.kcc.network",
    chainId: 322,
    symbol: "tKCS",
    block_explorer: "https://scan-testnet.kcc.network",
    type: "Testnet",
  },
  {
    network: "matic",
    name: "Matic Mainnet RPC",
    url: "https://polygon-rpc.com",
    chainId: 0x89,
    symbol: "MATIC",
    block_explorer: "https://explorer.matic.network/",
    type: "Mainnet",
  },
  {
    network: "matic",
    name: "Matic Testnet RPC",
    url: "https://rpc-mumbai.maticvigil.com",
    chainId: 0x13881,
    symbol: "MATIC",
    block_explorer: "https://mumbai.polygonscan.com/",
    type: "Testnet",
  },
  {
    network: "moonriver",
    name: "Moonriver Mainnet RPC",
    url: "https://rpc.moonriver.moonbeam.network",
    chainId: 1285,
    symbol: "MOVR",
    block_explorer: "https://blockscout.moonriver.moonbeam.network/",
    type: "Mainnet",
  },
  {
    network: "okex",
    name: "OKExChain Mainnet RPC",
    url: "https://exchainrpc.okex.org",
    chainId: 66,
    symbol: "OKT",
    block_explorer: "https://www.oklink.com/okexchain",
    type: "Mainnet",
  },
  {
    network: "telos",
    name: "Telos EVM Mainnet RPC",
    url: "https://mainnet.telos.net/evm",
    chainId: 40,
    symbol: "TLOS",
    block_explorer: "https://telos.net/",
    type: "Mainnet",
  },
  {
    network: "one",
    name: "Harmony Mainnet RPC",
    url: "https://api.harmony.one/",
    chainId: 0x63564c40,
    symbol: "ONE",
    block_explorer: "https://explorer.harmony.one",
    type: "Mainnet",
  },
  {
    network: "one",
    name: "Harmony Testnet RPC",
    url: "https://api.s0.b.hmny.io/",
    chainId: 0x6357d2e0,
    symbol: "ONE",
    block_explorer: "https://explorer.harmony.one",
    type: "Testnet",
  },
  {
    network: "ubiq",
    name: "Ubiq Mainnet RPC",
    url: "https://rpc.octano.dev/",
    chainId: 8,
    symbol: "UBQ",
    block_explorer: "https://ubiqscan.io/",
    type: "Mainnet",
  },
  {
    network: "gno",
    name: "Gnosis Mainnet RPC",
    url: "https://rpc.gnosischain.com/",
    chainId: 64,
    symbol: "XDAI",
    block_explorer: "https://blockscout.com/xdai/mainnet/",
    type: "Mainnet",
  },
  {
    network: "nahmii",
    name: "Nahmii Mainnet RPC",
    url: "https://l2.nahmii.io/",
    chainId: 5551,
    symbol: "ETH",
    block_explorer: "https://explorer.nahmii.io/",
    type: "Mainnet",
  },
  {
    network: "nahmii",
    name: "Nahmii Testnet RPC",
    url: "https://l2.testnet.nahmii.io/",
    chainId: 5553,
    symbol: "ETH",
    block_explorer: "https://explorer.testnet.nahmii.io/",
    type: "Testnet",
  },
  {
    network: "iotex",
    name: "IoTeX Mainnet RPC",
    url: "https://babel-api.mainnet.iotex.io",
    chainId: 4689,
    symbol: "IOTEX",
    block_explorer: "https://iotexscan.io/",
    type: "Mainnet",
  },
  {
    network: "hoo",
    name: "Hoo Mainnet RPC",
    url: "https://http-mainnet.hoosmartchain.com",
    chainId: 70,
    symbol: "HOO",
    block_explorer: "https://hooscan.com",
    type: "Mainnet",
  },
  {
    network: "celo",
    name: "Celo Mainnet RPC",
    url: "https://rpc.ankr.com/celo",
    chainId: 42220,
    symbol: "CELO",
    block_explorer: "https://celoscan.com",
    type: "Mainnet",
  },
  {
    network: "near",
    name: "Near Mainnet RPC",
    url: "https://rpc.ankr.com/near",
    chainId: null,
    symbol: "NEAR",
    block_explorer: "",
    type: "Mainnet",
  },
  {
    network: "arbitrum",
    name: "Arbitrum Mainnet RPC",
    url: "https://rpc.ankr.com/arbitrum",
    chainId: 42161,
    symbol: "ETH",
    block_explorer: "https://arbiscan.io/",
    type: "Mainnet",
  },
  {
    network: "solana",
    name: "Solana Mainnet RPC",
    url: "https://rpc.ankr.com/solana",
    chainId: null,
    symbol: "SOL",
    block_explorer: "https://solscan.io/",
    type: "Mainnet",
  },
  {
    network: "smartbch",
    name: "SmartBCH Mainnet RPC",
    url: "https://smartbch.fountainhead.cash/mainnet",
    chainId: 10000,
    symbol: "BCH",
    block_explorer: "https://www.smartscan.cash/",
    type: "Mainnet",
  },
];

export const RPC_NETWORKS = [
  {
    slug: "avax",
    network: "Avalanche",
    image: "/logos/avax.png",
    url: "https://www.avax.network/",
  },
  {
    slug: "bsc",
    network: "Binance Smart Chain",
    image: "/logos/bnb.png",
    url: "https://www.bnbchain.world/en",
  },
  {
    slug: "eth",
    network: "Ethereum",
    image: "/logos/eth.png",
    url: "//ethereum.org",
  },
  {
    slug: "ftm",
    network: "Fantom",
    image: "/logos/ftm.png",
    url: "https://fantom.foundation/",
  },
  {
    slug: "one",
    network: "Harmony",
    image: "/logos/harmony.png",
    url: "https://www.harmony.one/",
  },
  {
    slug: "heco",
    network: "Huobi Eco Chain",
    image: "/logos/heco.png",
    url: "https://www.hecochain.com",
  },
  {
    slug: "matic",
    network: "Polygon Matic",
    image: "/logos/matic.png",
    url: "https://polygon.technology/",
  },
  {
    slug: "kcc",
    network: "Kucoin Chain",
    image: "/logos/kcc.png",
    url: "https://www.kcc.io/",
  },
  {
    slug: "ela",
    network: "Elastos",
    image: "/logos/ela.png",
    url: "https://www.elastos.org/",
  },
  {
    slug: "gno",
    network: "Gnosis",
    image: "/logos/wxdai.png",
    url: "https://gnosis.io/",
  },
  {
    slug: "ubiq",
    network: "Ubiq",
    image: "/logos/ubiq.png",
    url: "https://ubiqsmart.com/",
  },
  {
    slug: "cro",
    network: "Cronos",
    image: "/logos/cro.svg",
    url: "https://cronos.org/",
  },
  {
    slug: "fuse",
    network: "Fuse",
    image: "/logos/fuse.png",
    url: "https://fuse.io/",
  },
  {
    slug: "moonriver",
    network: "Moonriver",
    image: "/logos/movr.webp",
    url: "https://moonbeam.network/networks/moonriver/",
  },
  {
    slug: "okex",
    network: "OKEx",
    image: "/logos/okt.webp",
    url: "https://www.okx.com/okc",
  },
  {
    slug: "telos",
    network: "Telos",
    image: "/logos/tlos.png",
    url: "https://www.telos.net/",
  },
  {
    slug: "nahmii",
    network: "Nahmii",
    image: "/logos/nii.webp",
    url: "https://www.nahmii.io/",
  },
  {
    slug: "iotex",
    network: "IoTeX",
    image: "/logos/iotex.webp",
    url: "https://iotex.io/",
  },
  {
    slug: "hoo",
    network: "Hoo",
    image: "/logos/hoo.png",
    url: "https://www.hoosmartchain.com/",
  },
  {
    slug: "celo",
    network: "Celo",
    image: null,
    url: "https://celo.org/",
  },
  {
    slug: "near",
    network: "Near",
    image: null,
    url: "https://near.org/",
  },
  {
    slug: "arbitrum",
    network: "Arbitrum",
    image: null,
    url: "https://offchainlabs.com/",
  },
  {
    slug: "solana",
    network: "Solana",
    image: null,
    url: "https://solana.com/",
  },
  {
    slug: "smartbch",
    network: "SmartBCH",
    image: null,
    url: "https://smartbch.org/",
  },
];
